# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_companies_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
