# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_companie_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companie',
            old_name='companies_logo',
            new_name='companie_logo',
        ),
    ]
