# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_companie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companie',
            name='nbEmployee',
        ),
    ]
